import { z } from "zod";

export const modify = {
  type: "modify",
  prompt_template: `Please revise the existing prompt to better capture the context and specifics of the request.
   Focus on clarifying the objectives, providing relevant details, and ensuring that the language is accessible and engaging.
    Aim for a clear and concise description that enhances understanding while retaining the original intent of the prompt.
    
    You are given the context and the current prompt below. Revise the prompt to improve its clarity and effectiveness.
    Context: 
    {context}



    Use the above context to refine the prompt for generating
    Don't add any context lines in the prompt. As these are already provided in the context.
    Only focus on the prompt lines.
    Current Prompt: 
    {prompt}

    
    Don't give output in doc string format
    `,
  schema: z.object({
    component: z.object({
      extract: z.string().describe("Modified Prompt generated by the LLM"),
      context: z
        .string()
        .describe("Context information for the generated component"),
    }),
  }),
};




export const describe = {
  type: "describe",
  prompt_template: `
  Describe the provided code snippet in detail, explaining its structure, functionality, and any potential improvements or modifications that could be made.
  You are given the current code snippet below. Describe the code snippet in detail, highlighting its key features, functionality, and structure.

  {context}

  Current Code Snippet:
  {prompt}



  Do not write code as the prompt description.
  explain the code snippet in detail. And only write the prompt don't give the whole code in return.


  
  `,
  schema: z.object({
    component: z.object({
      extract: z.string().describe("Described prompt of the code snippet generated by the LLM"),
      context: z
        .string()
        .describe("Context information for the generated component"),
    }),
  }),
};







export const normal = {
  type: "normal",
  prompt_template: `Generate a minimalistic and clean UI code based on the provided context and prompt.

Context: 
{context}

Only create the code snippet based on the prompt provided. Do not add any additional context or details.
The context is only provided to help you understand the requirements better.
Prompt: 
{prompt}

Requirements:
- Use React functional components and hooks (useState, useEffect).
- No external libraries or hooks unless absolutely necessary.
- Keep the structure simple and easy to understand.
- Focus on essential HTML elements and styling using basic inline CSS classes.

Generated Code:`,
  schema: z.object({
    component: z.object({
      extract: z.string().describe("React component code generated by the LLM"),
      context: z
        .string()
        .describe("Context information for the generated component"),
    }),
  }),
};
